### ISSUE TITLE
Pixelated image and text

### ISSUE THREAD

**Issue by jobil** [danielktaylor/fabric-js-editor#1]
Hi Daniel,

This frabricjs editor you made is freaking awesome! I think you made the exact editor I was looking for, for a project. I have a couple of questions. What is the license of your editor? I setup the editor locally and everything works great except one issue I noticed where images and text are pixelated. I found this [SO](http://stackoverflow.com/questions/35112585/blurry-image-in-canvas-when-using-fabricjs-1-5-0) and I tried to apply it but not having success. I am very new to fabricjs so not totally sure how to apply it. I also tried updating to the latest of fabricjs (1.6.4) which fixed the issue with the pixelation but created an issue with dragging objects (for example, when dragging a text object it doesn't add the box that allows you to rotate the text and also adds a cursor to create a new text object). Any tips on how to solve the pixelation issue? Thanks again for this awesome piece of software!

**Comment by danielktaylor** [comment]
I can take a pass at upgrading to fabric 1.6 later this week. Not sure how many changes they have made and whether it will break a lot of stuff.

**Comment by jobil** [comment]
Wow, that was fast! I just got the latest and images/text look perfect now. Thanks again!
