### ISSUE TITLE
SVG Import

### ISSUE THREAD

**Issue by mattsrinc** [danielktaylor/fabric-js-editor#12]
How it would be possible to add importing SVG images in the easiest way?

I see the insertSvg function in fabricUtils.js. Maybe adding some quick code to importExport.js and cloning UI elements in the sidebar to call it?

Possible ungrouping on load (and grouping/ungrouping of objects in general) would be fine too yet this is not that important as importing SVG images as a whole first. For inspiration:

[http://jsfiddle.net/unu2xLj9/](http://jsfiddle.net/unu2xLj9/)

**Comment by danielktaylor** [comment]
Yes, `insertSvg` is what you want to modify. Fabric's `loadSVGFromURL` (and related methods) can do 90% of the work.

**Comment by mattsrinc** [comment]
Thank you, will try that - and thanks for a nice editor. Still works as of Sep 2019, only filesaver module being deprecated now.
