### ISSUE TITLE
Font Size cannot be changed, uncommenting does not work. 

### ISSUE THREAD

**Issue by varunmehta** [danielktaylor/fabric-js-editor#3]
Uncommented the font size change dropdown, and it did not function as expected. 

**index.html (242-248)**
```
                <div id="toolbar-font-size" class="toolbar-item toolbar-input">
                  <input type="text" id="font-size" maxlength="3" class="toolbar-text-input">
                  <div class="toolbar-arrow"></div>
                </div>
                <div class="mdl-tooltip mdl-tooltip--large noselect" for="toolbar-font-size">Font Size</div>

                <div class="toolbar-separator"></div>
```

Any ideas if you can get it working ?

**Comment by danielktaylor** [comment]
Hi Varun,

You'll also need to uncomment the handler:

https://github.com/danielktaylor/fabric-js-editor/blob/49116fa5a0916f5d15c111d525e5e4279bd8cc10/src/js/app/handlers.js#L166

If I remember correctly, I removed the font-size selection in favor of letting the user manually drag the text to the desired size. It would have been hard to get both working correctly together. You could use the font size selector and disable draggable-resizing of text elements.

Happy to take pull requests if you get the two features to play nicely together, or if you add a feature switch.

**Comment by NewPrototype** [comment]
Can I add images? Not SVG

**Comment by danielktaylor** [comment]
Hi @NewPrototype -

The code currently supports SVG images. You can see the code that handles this here:

https://github.com/danielktaylor/fabric-js-editor/blob/master/src/js/app/fabricUtils.js#L330

If you want to support non-vector images, you'll need to extend that function. You can see how to add support for PNG's here:

https://stackoverflow.com/questions/44745476/is-there-a-way-to-import-an-image-file-using-fabric-js

**Comment by NewPrototype** [comment]
Ok, thank you. Go ahead
