### ISSUE TITLE
Problem building on linux. FileSaver.min.js

### ISSUE THREAD

**Issue by dominikveils** [danielktaylor/fabric-js-editor#4]
Hello,
There is a problem building the package on linux.
`Error: Cannot find module '../lib/filesaver.min.js'` I've got this when when trying to build it.
The solution is to change the filename of `src/js/lib/FileSaver.min.js` to `src/js/lib/filesaver.min.js`

**Comment by danielktaylor** [comment]
Doh! Stupid HFS+ case insensitivity.

Fixed. Thanks for reporting.
