### ISSUE TITLE
Unable to use the code

### ISSUE THREAD

**Issue by mbilwar** [danielktaylor/fabric-js-editor#5]
I think some files are missing. When i run the index.html file then it will throw globals.canvas error. I am new to fabric.js i have added all the necessary js files but still it is not working. 

Can you please provide more info (wiki) on this tool and few sample source code snippets how to use and run the existing code.

Thank you :)

**Comment by danielktaylor** [comment]
You're running this via the gulp file, yes?

> npm install
> gulp dev

You can't just open the html file. Type `gulp` and you'll see the list of gulp tasks. You can run `gulp prod` to generate the production files.
