### ISSUE TITLE
LGPL/Apache/MIT licensing?

### ISSUE THREAD

**Issue by timopulkkinen** [danielktaylor/fabric-js-editor#7]
Hello,

would it be possible to use LGPL, Apache or MIT licensing in addition to GPL?

**Comment by danielktaylor** [comment]
I'll take a look

**Comment by danielktaylor** [comment]
@timopulkkinen 

I've relicensed under the less restrictive MIT license.

Would love to know what the code gets used for, out of curiosity, but of course no obligation.
